"""
Coded by Wonnetz Phanthavong
Title: Even Fibonacci numbers
Difficulty Rating: 5%
Question:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

a = 2
x = 3
sum = 2

while x < 4000000:
    b = x
    x += a
    a = b
    if x % 2 ==0:
        sum += x
print(sum)

"""
Output: 4613732
"""